### ISSUE TITLE
Fix your image path

### ISSUE THREAD

**Issue by mlaplante** [derickwarshaw/firstrepository#1]
Right now your image path is relative to your desktop so it's not showing

**Comment by mlaplante** [comment]
Have an extra / in this image path.

Should be < img src = "" / > - Not to scale need spaces so you can see code

**Comment by derickwarshaw** [comment]
Pushed fix for issue 1 AND pushed css style sheet used in assignment 2
(even though you asked us to put it in style tags, sorry.)

Derick
