### ISSUE TITLE
Try to use psuedo selectors 

### ISSUE THREAD

**Issue by mlaplante** [derickwarshaw/firstrepository#10]
For your quantity class try to use a psuedo selector to accomplish the same goal.

for example:

instead of .quantity

td td:firstchild as the selector or something similiar

**Comment by derickwarshaw** [comment]
Hello,

I've restructured my repository to reflect the day1,day2.. assignment
structure. I just pushed fixes for issues 6,8,9, and 10. I thought I was
able to delete the old files that are not in their respective folders but
it looks like it didn't work. Maybe we can look at that tomorrow. Thanks,

Derick

On Wed, Jan 14, 2015 at 1:10 PM, Michael La Plante <notifications@github.com
