### ISSUE TITLE
Look into the === js operator

### ISSUE THREAD

**Issue by mlaplante** [derickwarshaw/firstrepository#22]
Just know the difference between that and the ==

**Comment by derickwarshaw** [comment]
Good call - I did some review and found this post on stackoverflow : http://stackoverflow.com/questions/8132353/what-is-the-difference-between-and-in-javascript


== attempts to convert the values to the same type before testing if they're the same. "5" == 5
=== does not do this; it requires objects to be of the same type to be equal. "5" !== 5
In this case, the result is:

x == undefined will be true if x is undefined or null.
x === undefined will only be true if x is undefined.
You should prefer the first method if you'd like undefined and null to be treated equivalently. One common use of this is optional function arguments.

function greet(name, greeting) {
    if (name == undefined) name = 'World';
    if (greeting == undefined) greeting = 'Hello';
    alert(greeting + ' ' + name);
}

greet(); // alerts "Hello World"
greet("Bob"); // alerts "Hello Bob"
greet(null, "Goodbye"); // alerts "Goodbye World"
